[package]
name = "aldoas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.0", features = ["cargo"] }
color-eyre = "0.6.2"
duct = "0.13.7"
pam = "0.7.0"
rpassword = "7.3.1"
